import { Analytics } from "@vercel/analytics/next"
import { SpeedInsights } from "@vercel/speed-insights/next"
import type { Metadata } from "next";
import Link from 'next/link';
import "./globals.css";
import "@wooorm/starry-night/style/tritanopia-light";
import 'katex/dist/katex.min.css';
import HamburgerMenu from "@/components/hamburgerMenu";

import { Roboto_Mono } from 'next/font/google'

const robotoMono = Roboto_Mono({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Analytics />
        <SpeedInsights />
        <div className="flex flex-row justify-center mt-[40px]">
          <div className="xl:w-[70%] 2xl:w-[60%] w-[95%]">
            <div className="flex flex-row justify-between items-center xl:pl-[15px] xl:pr-[15px] pr-[15px] mb-[20px]">
              <h1 className={`whitespace-nowrap text-xl text-left inline xl:ml-[1px] pb-[0px] ml-[10px] ${robotoMono.className}`}>
                <Link href="/">Aditya Ambadipudi</Link>
              </h1>
              <HamburgerMenu/>
              <div className="whitespace-nowrap inline font-mono pb-[0px] align text-base space-x-6 text-gray-600 hidden xl:block">
                  <Link href="/posts">All posts</Link> 
                  <Link href="/interestingLinks">Interesting papers/articles</Link> 
                  <Link href="/bookReports">Book reports</Link>
                  <Link href="/chessPuzzles">Chess puzzles</Link>
              </div>
            </div>
            
            <div className="xl:p-[20px] xl:pl-[35px] xl:pr-[35px] pt-[20px]">
              
              {children}
            </div>
          </div>

          <div className="shrink-0 w-[10%] bg-red-50 h-600 shrink-0 hidden">AD</div>
        </div>
        
        
      </body>
    </html>
  );
}