import type { Metadata } from "next";
import Head from "next/head";
import "./globals.css";
import "@wooorm/starry-night/style/tritanopia-light";
import 'katex/dist/katex.min.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-row justify-center m-[50px]">
          <div className="w-[50%] shrink-0">
            <h1 className="font-sans font-thin text-7xl text-center">ADITYA AMBADIPUDI</h1>
            <div className="flex gap-10 justify-center text-2xl m-[30px] my-0.25  border-dotted border-b-2 pb-[30px]">
              <a href="#">All posts</a> ★
              <a href="#">About me</a> ★
              <a href="#">Socials</a>
            </div>
            <div className="p-[20px]">
            {children}
            </div>
          </div>
          <div className="shrink-0 w-[10%] bg-red-50 h-600 shrink-0 hidden">AD</div>
        </div>
        
      </body>
    </html>
  );
}