import type { Metadata } from "next";
import "./globals.css";
import "@wooorm/starry-night/style/tritanopia-light";
import 'katex/dist/katex.min.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-row justify-center m-[10px]">
          <div className="w-[60%]">
            <div className="flex flex-row justify-between border-b border-gray-200 pl-[35px] pr-[35px] p-[5px] mb-[10px]">
              <h1 className="font-mono font-bold text-xl text-left">Aditya Ambadipudi</h1>
              <div className="flex text-base space-x-6 text-gray-600">
                  <a href="/posts">All posts</a> 
                  <a href="/interestingLinks">Interesting papers/articles</a> 
                  <a href="/bookReports">Book reports</a>
                  <a href="/chessPuzzles">Chess puzzles</a>
              </div>
            </div>
            
            <div className="p-[20px] pl-[35px] pr-[35px] ">
              {children}
            </div>
          </div>

          <div className="shrink-0 w-[10%] bg-red-50 h-600 shrink-0 hidden">AD</div>
        </div>
        
        
      </body>
    </html>
  );
}